# Generated by Django 5.0.14 on 2025-11-27 05:57

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, help_text="Blocked IP address", unique=True),
                ),
                ("reason", models.TextField(blank=True, help_text="Reason for blocking")),
                ("blocked_at", models.DateTimeField(auto_now_add=True, help_text="When the IP was blocked")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="When the block expires (null = permanent)", null=True),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether block is active")),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who blocked this IP",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_ips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked IP",
                "verbose_name_plural": "Blocked IPs",
                "db_table": "security_blocked_ips",
                "ordering": ["-blocked_at"],
            },
        ),
        migrations.CreateModel(
            name="RateLimitViolation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("endpoint", models.CharField(help_text="Rate limited endpoint", max_length=500)),
                ("limit_type", models.CharField(help_text="Type of rate limit", max_length=50)),
                ("request_count", models.IntegerField(help_text="Number of requests in window")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Limit Violation",
                "verbose_name_plural": "Rate Limit Violations",
                "db_table": "security_rate_limit_violations",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(db_index=True, help_text="Client IP address")),
                ("method", models.CharField(help_text="HTTP method", max_length=10)),
                ("path", models.CharField(help_text="Request path", max_length=500)),
                ("query_string", models.TextField(blank=True, help_text="Query string")),
                ("user_agent", models.TextField(blank=True, help_text="User agent")),
                ("status_code", models.IntegerField(blank=True, help_text="HTTP status code", null=True)),
                ("response_time_ms", models.IntegerField(blank=True, help_text="Response time in ms", null=True)),
                ("country", models.CharField(blank=True, help_text="Country from GeoIP", max_length=100)),
                ("city", models.CharField(blank=True, help_text="City from GeoIP", max_length=100)),
                ("is_suspicious", models.BooleanField(default=False, help_text="Flagged as suspicious")),
                ("blocked", models.BooleanField(default=False, help_text="Request was blocked")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "db_table": "security_request_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["ip_address", "timestamp"], name="security_re_ip_addr_7dd674_idx"),
                    models.Index(fields=["user", "timestamp"], name="security_re_user_id_2d4711_idx"),
                    models.Index(fields=["is_suspicious"], name="security_re_is_susp_8a6d24_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Password Changed"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("IP_BLOCKED", "IP Blocked"),
                            ("IP_UNBLOCKED", "IP Unblocked"),
                            ("RATE_LIMITED", "Rate Limited"),
                            ("SUSPICIOUS", "Suspicious Activity"),
                            ("DATA_ACCESS", "Sensitive Data Access"),
                            ("DATA_EXPORT", "Data Export"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Event description")),
                ("ip_address", models.GenericIPAddressField(blank=True, help_text="Source IP", null=True)),
                ("metadata", models.JSONField(blank=True, help_text="Additional event data", null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Event",
                "verbose_name_plural": "Security Events",
                "db_table": "security_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["event_type", "timestamp"], name="security_ev_event_t_efa0a0_idx"),
                    models.Index(fields=["severity", "timestamp"], name="security_ev_severit_db68de_idx"),
                    models.Index(fields=["user", "timestamp"], name="security_ev_user_id_6a5f21_idx"),
                ],
            },
        ),
    ]
