# Generated by Django 5.0.14 on 2025-11-27 05:57

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, help_text="Service code", max_length=20, unique=True)),
                ("name", models.CharField(help_text="Service name", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Service description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consultation"),
                            ("LABORATORY", "Laboratory Tests"),
                            ("PHARMACY", "Pharmacy"),
                            ("RADIOLOGY", "Radiology"),
                            ("PROCEDURE", "Medical Procedure"),
                            ("ADMISSION", "Hospital Admission"),
                            ("SURGERY", "Surgery"),
                            ("EMERGENCY", "Emergency Services"),
                            ("OTHER", "Other Services"),
                        ],
                        default="OTHER",
                        help_text="Service category",
                        max_length=20,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price in KES",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether service is available")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "billing_services",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "invoice_number",
                    models.CharField(db_index=True, help_text="Invoice number", max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Payment"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="DRAFT",
                        help_text="Invoice status",
                        max_length=20,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(default=django.utils.timezone.now, help_text="Date invoice was issued"),
                ),
                ("due_date", models.DateField(help_text="Payment due date")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Subtotal before tax/discount",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), help_text="Tax amount", max_digits=10
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), help_text="Discount amount", max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), help_text="Total amount due", max_digits=12
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), help_text="Amount already paid", max_digits=12
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), help_text="Remaining balance", max_digits=12
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the invoice",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient being billed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "billing_invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MPESA", "M-Pesa"),
                            ("CASH", "Cash"),
                            ("CARD", "Credit/Debit Card"),
                            ("INSURANCE", "Insurance"),
                            ("BANK", "Bank Transfer"),
                        ],
                        default="MPESA",
                        help_text="Payment method",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        default="PENDING",
                        help_text="Payment status",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, help_text="M-Pesa phone number", max_length=15)),
                (
                    "merchant_request_id",
                    models.CharField(blank=True, db_index=True, help_text="M-Pesa MerchantRequestID", max_length=100),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, db_index=True, help_text="M-Pesa CheckoutRequestID", max_length=100),
                ),
                (
                    "mpesa_receipt_number",
                    models.CharField(blank=True, db_index=True, help_text="M-Pesa Receipt Number", max_length=50),
                ),
                ("transaction_date", models.DateTimeField(blank=True, help_text="M-Pesa Transaction Date", null=True)),
                ("result_code", models.CharField(blank=True, help_text="M-Pesa Result Code", max_length=10)),
                ("result_description", models.TextField(blank=True, help_text="M-Pesa Result Description")),
                ("callback_data", models.JSONField(blank=True, help_text="Raw callback data", null=True)),
                ("reference", models.CharField(blank=True, help_text="Payment reference", max_length=100)),
                ("notes", models.TextField(blank=True, help_text="Payment notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice being paid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who processed the payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "billing_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("description", models.CharField(blank=True, help_text="Item description", max_length=500)),
                ("quantity", models.PositiveIntegerField(default=1, help_text="Quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total price (quantity * unit_price)",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Parent invoice",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.invoice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service being billed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_items",
                        to="billing.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
                "db_table": "billing_invoice_items",
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="billing_inv_status_aefe38_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["due_date"], name="billing_inv_due_dat_cedac3_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["patient", "status"], name="billing_inv_patient_0d3a1e_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="billing_pay_status_d79ab7_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_method"], name="billing_pay_payment_595f7b_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["created_at"], name="billing_pay_created_bef6a9_idx"),
        ),
    ]
