# Generated by Django 5.0.14 on 2025-11-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(auto_now_add=True, help_text="Date invoice was issued"),
        ),
    ]
