# Generated by Django 5.0.14 on 2025-11-26 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "order_number",
                    models.CharField(db_index=True, help_text="Unique order number", max_length=20, unique=True),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("ROUTINE", "Routine"), ("URGENT", "Urgent"), ("STAT", "STAT (Immediate)")],
                        default="ROUTINE",
                        help_text="Order priority",
                        max_length=10,
                    ),
                ),
                ("clinical_notes", models.TextField(blank=True, help_text="Clinical indication/reason for test")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COLLECTED", "Collected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESULTED", "Resulted"),
                            ("REVIEWED", "Reviewed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current order status",
                        max_length=15,
                    ),
                ),
                (
                    "specimen_collected_at",
                    models.DateTimeField(blank=True, help_text="When specimen was collected", null=True),
                ),
                ("ordered_at", models.DateTimeField(auto_now_add=True, help_text="When order was placed")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Last update timestamp")),
            ],
            options={
                "verbose_name": "Lab Order",
                "verbose_name_plural": "Lab Orders",
                "db_table": "lab_orders",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hl7_obr_segment", models.TextField(blank=True, help_text="HL7 OBR (Observation Request) segment")),
                (
                    "hl7_obx_segments",
                    models.TextField(blank=True, help_text="HL7 OBX (Observation Result) segments, one per line"),
                ),
                ("result_summary", models.TextField(blank=True, help_text="Human-readable result summary")),
                (
                    "is_abnormal",
                    models.BooleanField(default=False, help_text="Whether any results are outside normal range"),
                ),
                (
                    "is_critical",
                    models.BooleanField(default=False, help_text="Whether results require immediate attention"),
                ),
                ("resulted_at", models.DateTimeField(auto_now_add=True, help_text="When results were entered")),
                ("reviewed_at", models.DateTimeField(blank=True, help_text="When results were reviewed", null=True)),
                ("review_notes", models.TextField(blank=True, help_text="Notes from reviewing physician")),
            ],
            options={
                "verbose_name": "Lab Result",
                "verbose_name_plural": "Lab Results",
                "db_table": "lab_results",
                "ordering": ["-resulted_at"],
            },
        ),
        migrations.CreateModel(
            name="TestType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        db_index=True, help_text="Test code (e.g., CBC, BMP, UA)", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Full test name", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Test description and purpose")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HEMATOLOGY", "Hematology"),
                            ("CHEMISTRY", "Chemistry"),
                            ("MICROBIOLOGY", "Microbiology"),
                            ("URINALYSIS", "Urinalysis"),
                            ("IMMUNOLOGY", "Immunology"),
                            ("COAGULATION", "Coagulation"),
                            ("BLOOD_BANK", "Blood Bank"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Test category",
                        max_length=20,
                    ),
                ),
                ("loinc_code", models.CharField(blank=True, help_text="LOINC code for standardization", max_length=20)),
                (
                    "specimen_type",
                    models.CharField(default="Blood", help_text="Required specimen type", max_length=100),
                ),
                (
                    "turnaround_hours",
                    models.PositiveIntegerField(default=24, help_text="Expected turnaround time in hours"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this test is currently offered")),
            ],
            options={
                "verbose_name": "Test Type",
                "verbose_name_plural": "Test Types",
                "db_table": "lab_test_types",
                "ordering": ["category", "name"],
            },
        ),
    ]
