# Generated by Django 5.0.14 on 2025-11-26 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab_orders", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="laborder",
            name="ordering_provider",
            field=models.ForeignKey(
                help_text="Doctor who ordered the test",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordered_labs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient for this order",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_orders",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="specimen_collected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who collected the specimen",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collected_specimens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="order",
            field=models.OneToOneField(
                help_text="Associated lab order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="lab_orders.laborder",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="resulted_by",
            field=models.ForeignKey(
                help_text="Lab tech who entered results",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entered_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor who reviewed results",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="test_type",
            field=models.ForeignKey(
                help_text="Type of test ordered",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="lab_orders.testtype",
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["status", "priority"], name="lab_orders_status_7f4aa6_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["patient", "status"], name="lab_orders_patient_d15a9f_idx"),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(fields=["ordering_provider", "status"], name="lab_orders_orderin_473844_idx"),
        ),
    ]
