# Generated by Django 5.0.14 on 2025-11-26 18:50

import apps.patients.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the patient",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mrn",
                    models.CharField(
                        db_index=True,
                        default=apps.patients.models.generate_mrn,
                        help_text="Medical Record Number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(help_text="Patient first name", max_length=100)),
                ("last_name", models.CharField(help_text="Patient last name", max_length=100)),
                ("middle_name", models.CharField(blank=True, help_text="Patient middle name", max_length=100)),
                ("date_of_birth", models.DateField(help_text="Date of birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other"), ("U", "Unknown")],
                        default="U",
                        help_text="Patient gender",
                        max_length=1,
                    ),
                ),
                ("_ssn_encrypted", models.BinaryField(blank=True, help_text="Encrypted SSN (AES-256-GCM)", null=True)),
                (
                    "ssn_hash",
                    models.CharField(
                        blank=True, db_index=True, help_text="SHA-256 hash of SSN for lookups", max_length=64, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 9-15 digits", regex="^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, help_text="Email address", max_length=254)),
                ("address_line1", models.CharField(blank=True, help_text="Street address line 1", max_length=200)),
                ("address_line2", models.CharField(blank=True, help_text="Street address line 2", max_length=200)),
                ("city", models.CharField(blank=True, help_text="City", max_length=100)),
                ("state", models.CharField(blank=True, help_text="State/Province", max_length=50)),
                ("postal_code", models.CharField(blank=True, help_text="ZIP/Postal code", max_length=20)),
                ("country", models.CharField(default="USA", help_text="Country", max_length=50)),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A Positive"),
                            ("A-", "A Negative"),
                            ("B+", "B Positive"),
                            ("B-", "B Negative"),
                            ("AB+", "AB Positive"),
                            ("AB-", "AB Negative"),
                            ("O+", "O Positive"),
                            ("O-", "O Negative"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        help_text="Blood type",
                        max_length=4,
                    ),
                ),
                ("allergies", models.TextField(blank=True, help_text="Known allergies (comma-separated)")),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, help_text="Emergency contact name", max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, help_text="Emergency contact phone", max_length=20),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, help_text="Relationship to patient", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether patient record is active")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When the patient was registered")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When the patient record was last updated"),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "patients",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["last_name", "first_name"], name="patients_last_na_ce6411_idx"),
                    models.Index(fields=["date_of_birth"], name="patients_date_of_24544d_idx"),
                    models.Index(fields=["is_active"], name="patients_is_acti_4a96f9_idx"),
                ],
            },
        ),
    ]
